[package]
name = "fylm"
version = "0.1.0"
authors = ["torao <koiroha@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "^0.10"
failure = "^0.1"
clap = "^2.33"
nom = "^5.0.1"
